server:
  port: 8080

spring:
  application:
    name: gateway-service

# Configuración de los microservicios
microservices:
  review-service:
    url: http://localhost:8081
  user-service:
    url: http://localhost:8082
  course-service:
    url: http://localhost:8083
  content-service:
    url: http://localhost:8084

# Configuración de Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Actuator para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    cl.maotech.gateway_service: DEBUG
    feign: DEBUG